name: Snap Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Snap
        run: snap build --dangerous --revision=latest --snap=mimo2-6-distill
      - name: Test Snap
        run: snap install --dangerous --snap=mimo2-6-distill
        # Run validation tests for CPU engine
        snap run --snap=mimo2-6-distill test-engine --engine=cpu
