name: Inference Snap CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: Add steps to build the snap
      - name: Build Snap
        run: snap build --dangerous --revision=latest --snap=mimo2-6-distill
      # TODO: Add steps to test the snap locally
      - name: Local Test
        run: snap install --dangerous --snap=mimo2-6-distill
        # Followed by modelctl/inference validation
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Inference Tests
        run: snap run --snap=mimo2-6-distill test-engine --engine=cpu
