name: Snap Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    name: Publish Snap
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    env:
      SNAP_NAME: mimo2-6-distill
      REPO_NAME: mimo-snap
    steps:
    - uses: actions/checkout@v3
    - name: Tagging Snap
      run: snap publish --snap ${{ env.SNAP_NAME }} --channel stable
      env:
        # Requires STORE_LOGIN_MAIN secret for publishing
        STORE_LOGIN: ${{ secrets.STORE_LOGIN_MAIN }}
    
# TODO: Add automated changelog generation.